server:
  servlet:
    context-path: /twitter-gateway
logging:
  level:
    root: INFO

application:
  home:
    msg: Service is Up

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysqlDB
    username: dev1
    password: dev1
    #driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto : create-drop
    generate-ddl: true
    show-sql: true