server:
  servlet:
    context-path: /twint-wrapper
logging:
  level:
    root: INFO

application:
  home:
    msg: Service is Up
  twintcall:
    nb-core-threads: 24
    nb-max-threads: 80
    nb-queue-threads: 64
    grp-nb-core-threads: 4
    grp-nb-max-threads: 4
    twint_request_maximum_days : 15
    twint_big_request_subdivisions : 6
    twint_thread_nb_restart_on_error : 3
  elasticsearch:
    url: ${ES_URL:elasticsearch:9200}
    host: ${ES_HOST:localhost}
    port: ${ES_PORT:9200}
  twittie:
    url: ${TWITTIE_URL:http://185.249.140.38/weverify-twitie/process?annotations=:Person,:UserID,:Location,:Organization}
    


spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3308/twint-wrapper?serverTimeZone=CET&useSSL=false}
    username: ${MYSQL_USER:dev1}
    password: ${MYSQL_PASSWD:dev1}
    #driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto : create-drop
    generate-ddl: true
    show-sql: false

command:
  twint: docker run --rm --network dev_esnet -i medialab.registry.afp.com/twint:2.1.2
 
---
spring:
  profiles: dev    
 
---
spring:
  profiles: prod 
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
      
command:
  twint: 
 
 