server:
  servlet:
    context-path: /twitter-gateway
logging:
  level:
    root: INFO

application:
  home:
    msg: Service is Up
  twintcall:
    nb-core-threads: 4
    nb-max-threads: 4
    
  elasticsearch:
    url: ${ES_URL:elasticsearch:9200}
  

spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3308/twitter-gateway?serverTimeZone=CET&useSSL=false}
    username: dev1
    password: dev1
    #driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto : create-drop
    generate-ddl: true
    show-sql: true

command:
  twint: docker run --rm --network twint_esnet -i medialab.registry.afp.com/twint:2.1.2
 
---
spring:
  profiles: dev    
 
---
spring:
  profiles: prod 
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
      
command:
  twint: 
 
 