server:
  servlet:
    context-path: /twint-wrapper
  port: 8080
logging:
  level:
    root: INFO

application:
  home:
    msg: Service is Up
  twintcall:
    nb-core-threads: 24
    nb-max-threads: 80
    nb-queue-threads: 64
    grp-nb-core-threads: 4
    grp-nb-max-threads: 4
    twint_request_maximum_days : 15
    twint_big_request_subdivisions : 6
    twint_thread_nb_restart_on_error : 3
  elasticsearch:
    url: ${ES_URL:elasticsearch:9200}
    host: ${ES_HOST:localhost}
    port: ${ES_PORT:9200}
    
  twitie:
    url: ${TWITIE_URL:http://localhost:8081/process}
    threads: ${TWITIE_THREADS:8}
    es:
      pagesize: ${TWITIE_ES_PAGESIZE:100}
      bulksize: ${TWITIE_ES_BULKSIZE:5000}
  notification:
    slack: ${SLACK_URL:}
  actuator:
    user: ${ACTUATOR_USER:actuator}
    #password is generate with GeneratePassword class default is "actuator"
    passwd: ${ACTUATOR_PASSWORD:{bcrypt}$2a$10$haLsRQkZdhF1FtzV4iXFi.MiPOlDKN.i4FaWrjitA3eDFwoWeuMa2}
  

spring:
  application:
    name: twint-wrapper
    admin:
      enabled: true
  jackson:
    time-zone: Europe/Paris
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${FUSIONAUTH_ISSUER:weverify.eu}
          jwk-set-uri: ${FUSIONAUTH_URL:http://localhost:9011}/.well-known/jwks.json

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3308/twint-wrapper?serverTimezone=CET&useSSL=false}
    username: ${MYSQL_USER:dev1}
    password: ${MYSQL_PASSWD:dev1}
    #driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto : none
    hibernate.use-new-id-generator-mappings : false
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    generate-ddl: true
    show-sql: true

command:
  twint: docker run --rm --network dev_esnet -i twintplus:0.5

management:
 # server:
  #  port: 8111
  endpoints:
   enabled-by-default: false
   web:
      exposure:
        include:
        - health
        - info
        - loggers
      base-path: /manage
      
  endpoint:
    health:
      enabled: true
      show-details: when-authorized
      show-components: when-authorized
    info:
      enabled: true
    loggers:
      enabled: true
  info:
    git:
      mode: full  
---
spring:
  profiles: dev
  jpa:
    hibernate.ddl-auto: update
---
spring:
  profiles: demo
server:
  servlet:
    session:
      cookie:
        secure: false
command:
   twint:
---
server:
  servlet:
    context-path: /
spring:
  profiles: prod 
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
      
command:
  twint: 
 
 