version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
      
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: devpass123
        MYSQL_USER: dev1
        MYSQL_PASSWORD: dev1
        MYSQL_DATABASE: twint-wrapper
        TZ: Europe/Paris
    volumes:
      - mysqldata1:/var/lib/mysql
      - ./fusionauth-2020-weverify.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3308:3306
    networks:
      - esnet
  
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    environment:
      - cluster.name=fusionauth
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - esnet
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_fusion_data:/usr/share/elasticsearch/data
     
  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - mysql
      - search
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/fusionauth
      DATABASE_ROOT_USER: root
      DATABASE_ROOT_PASSWORD: devpass123
      DATABASE_USER: dev1
      DATABASE_PASSWORD: dev1
      FUSIONAUTH_MEMORY: 256M
      FUSIONAUTH_SEARCH_SERVERS: http://search:9200
      FUSIONAUTH_URL: http://fusionauth:9011
    networks:
     - esnet
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config 
volumes:
  mysqldata1:
  esdata1:
  es_fusion_data:
  fa_config:
  
networks:
  esnet:

  