version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
      
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: devpass123
        MYSQL_USER: dev1
        MYSQL_PASSWORD: dev1
        MYSQL_DATABASE: twint-wrapper
        TZ: UTC
    volumes:
      - mysqldata1:/var/lib/mysql
      - ./fusionauth-2020-weverify.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3308:3306
    networks:
      - esnet
     
  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - mysql
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/fusionauth?serverTimezone=UTC
      DATABASE_ROOT_USERNAME: root
      DATABASE_ROOT_PASSWORD: devpass123
      DATABASE_USERNAME: dev1
      DATABASE_PASSWORD: dev1
      FUSIONAUTH_APP_MEMORY: 256M
      SEARCH_TYPE: database
      FUSIONAUTH_APP_URL: http://fusionauth:9011
    networks:
     - esnet
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config
  
  #Twitie 
  spacy-de:
    image: registry.gitlab.com/european-language-grid/usfd/elg-spacy-ner/de:latest
    networks:
      - esnet
  spacy-el:
    image: registry.gitlab.com/european-language-grid/usfd/elg-spacy-ner/el:latest
    networks:
      - esnet
  spacy-en:
    image: registry.gitlab.com/european-language-grid/usfd/elg-spacy-ner/en:latest
    networks:
      - esnet
  spacy-es:
    image: registry.gitlab.com/european-language-grid/usfd/elg-spacy-ner/es:latest
    networks:
      - esnet
  spacy-fr:
    image: registry.gitlab.com/european-language-grid/usfd/elg-spacy-ner/fr:latest
    networks:
      - esnet
  spacy-it:
    image: registry.gitlab.com/european-language-grid/usfd/elg-spacy-ner/it:latest
    networks:
      - esnet
  spacy-pt:
    image: registry.gitlab.com/european-language-grid/usfd/elg-spacy-ner/pt:latest
    networks:
      - esnet
  spacy-multi-lingual:
    image: registry.gitlab.com/european-language-grid/usfd/elg-spacy-ner/multi-lingual:latest
    networks:
      - esnet    
  
  weverify-twitie:
    container_name: twitie
    image: registry.gitlab.com/european-language-grid/usfd/gate-ie-tools/twitie-multi-lingual:latest
    restart: always
    networks:
      - esnet
    ports:
      - 8081:8080
    depends_on:
      - spacy-de
      - spacy-el
      - spacy-en
      - spacy-es
      - spacy-fr
      - spacy-it
      - spacy-pt
      - spacy-multi-lingual
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
        labels: "twitie-log"   
    
volumes:
  mysqldata1:
  esdata1:
  es_fusion_data:
  fa_config:
  
networks:
  esnet:

  