version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml  
    ports:
      - 5601:5601
    networks:
      - esnet
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 83:80
    networks:
      - esnet
      
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: devpass123
        MYSQL_USER: dev1
        MYSQL_PASSWORD: dev1
        MYSQL_DATABASE: twint-wrapper
    container_name: mysql
    volumes:
      - mysqldata1:/usr/share/mysql/data
    ports:
      - 3308:3306
    networks:
      - esnet
      
volumes:
  esdata1: {}  
  mysqldata1: {}
networks:
  esnet:
  