version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: devpass123
        MYSQL_USER: dev1
        MYSQL_PASSWORD: dev1
        MYSQL_DATABASE: RequestInformation
    container_name: mysql
    volumes:
      - mysqldata1:/usr/share/mysql/data
    ports:
      - 3306:3306

volumes:
  mysqldata1: {}

