version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: on-failure
    environment:
        MYSQL_ROOT_PASSWORD: devpass123
        MYSQL_USER: dev1
        MYSQL_PASSWORD: dev1
        MYSQL_DATABASE: twint-wrapper
    container_name: mysql
    volumes:
      - mysqldata1:/var/lib/mysql
      - ./fusionauth-2020-weverify.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3308:3306
    networks:
      - esnet
      
  twint-wrapper:
    image: twint-wrapper:1.1.0
    container_name: twint-wrapper
    restart: on-failure
    depends_on:
      - mysql
    networks:
      - esnet
    ports:
      - 8282:8080
    environment:
      MYSQL_URL: "jdbc:mysql://mysql:3306/twint-wrapper?serverTimezone=CET&useSSL=false"
      ES_URL: elasticsearch:9200
      ES_HOST: elasticsearch
      FUSIONAUTH_URL: http://fusionauth:9011
      FUSIONAUTH_ISSUER: weverify.eu
      TWITTIE_URL: "http://twitie:8080/gate/process?annotations=:Person,:UserID,:Location,:Organization"
      PROFILE: demo,default
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-size: "200k"
        labels: "twint-wrapper"
  
  twitie:
    container_name: twitie
    image: registry.gitlab.com/european-language-grid/usfd/gate-ie-tools/twitie-snapshot:latest
    restart: always
    networks:
      - esnet
    ports:
      - 8081:8080
    environment:
      ELG_CONCURRENCY: 4
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
        labels: "twitie-log"


  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    environment:
      - cluster.name=fusionauth
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - esnet
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_fusion_data:/usr/share/elasticsearch/data
     
  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - mysql
      - search
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/fusionauth?serverTimezone=CET
      DATABASE_ROOT_USER: root
      DATABASE_ROOT_PASSWORD: devpass123
      DATABASE_USER: dev1
      DATABASE_PASSWORD: dev1
      FUSIONAUTH_MEMORY: 256M
      FUSIONAUTH_SEARCH_SERVERS: http://search:9200
      FUSIONAUTH_URL: http://fusionauth:9011
    networks:
     - esnet
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config 
      
      
volumes:
  esdata1: {}
  mysqldata1: {}
  fa_config: {}
  es_fusion_data: {}
  
networks:
  esnet:
  