version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
      
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: devpass123
        MYSQL_USER: dev1
        MYSQL_PASSWORD: dev1
        MYSQL_DATABASE: twitter-gateway
    container_name: mysql
    volumes:
      - mysqldata1:/usr/share/mysql/data
    ports:
      - 3308:3306
    networks:
      - esnet
      
  twint-gateway:
    image: medialab.registry.afp.com/twint-gateway:1.0
    container_name: twint-gateway
    restart: on-failure
    depends_on:
      - mysql
    networks:
      - esnet
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      MYSQL_URL: "jdbc:mysql://mysql:3306/twitter-gateway?serverTimeZone=CET&useSSL=false"
      ES_URL: elasticsearch:9200
volumes:
  esdata1: {}  
  mysqldata1: {}
networks:
  esnet:
  